#!/usr/bin/env bash

# NOTE: crispy-doom has some 1-time set up which must be performed, details here:
#       https://github.com/fabiangreffrath/crispy-doom/wiki/Building-on-Linux

source .env
CC=$LLVM_INSTALLDIR/bin/clang
# these were generated by observing the CFLAG values generated in the normal makefile for crispy doom, and then copy-pasted here
# did this so that I can specify the -fembed-bitcode=all -save-temps=obj flags necessary for OPTI-ML
CFLAGS="-O2 -g -Wall -Wdeclaration-after-statement -Wredundant-decls  -I/usr/include/SDL2 -D_REENTRANT   -I/usr/include/libpng16  -I/usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include -I/usr/include/opus -I/usr/include/aarch64-linux-gnu -I/usr/include/dbus-1.0 -I/usr/lib/aarch64-linux-gnu/dbus-1.0/include -I/usr/include/libinstpatch-2 -pthread -I/usr/include/SDL2 -D_REENTRANT -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -fembed-bitcode=all -save-temps=obj"

cd $HOME/crispy-doom
make clean
bear -- make CC=$CC CFLAGS="${CFLAGS}"
